### ISSUE TITLE
i want to remove /#/ from url 

### ISSUE THREAD

**Issue by prabhatmech** [gopar/OhMyCommand#1]
Hi I would like to thanks about your video and github repository .

I followed your all 3 videos for this OhMyCommand .
its really helping me to understand drf . i am requesting you to upload videos for this tutorial
. well i want to remove /#/ from url .
/#/ ,--> /       home page 
/#/login --> /login
/#/register  --> /register

can you help me how to do this ?

**Comment by gopar** [comment]
Hey!

Well I'm happy there's at least someone watching them :)

I believe you can add this to the end of the  `configFunction` in the `app.config.js` file.

```
// use the HTML5 History API
$locationProvider.html5Mode(true);
```

Also make sure to change this line to include the `$locationProvider`.

```
configFunction.$inject = ['$resourceProvider', '$httpProvider'];
```

To

```
configFunction.$inject = ['$resourceProvider', '$httpProvider', '$locationProvider'];
```

And I might have to restart the tutorial of OhMyCommand, I won't have time to finish it anytime soon. :'(
